[[news]]
date = "2026-06"
content = "论文被 Optica 接收了！🎉🎉🎉"

[[news]]
date = "2026-06"
content = "入职成都理工大学 · 物理学院。🎉🎉🎉"

[[news]]
date = "2025-09"
content = "论文发表于 Light: Science & Applications！🎉🎉🎉"

[[news]]
date = "2025-06"
content = "论文发表于 Nano Letters！🎉🎉🎉"

[[news]]
date = "2025-01"
content = "在南洋理工大学申艺杰教授课题组开始博士后研究。🎉🎉🎉"

[[news]]
date = "2024-06"
content = "在深圳大学通过博士学位论文答辩。🎉🎉🎉"
